services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=hoidanit
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../BE_docker_demo
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../FE_docker_demo/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p fullstack-docker up -d
